---

- name: Install PPAs
  apt_repository: repo={{item}} update_cache=yes
  with_items:
  - ppa:pbek/qownnotes

- name: Install Packages
  apt: name={{item}} state=present # update_cache=yes
  with_items:
  - qownnotes
