---

- name: Get release info
  github_release:
     action: latest_release
     repo: simplenote-electron
     user: Automattic

- name: Downloading simplenote
  uri:
    url: https://api.github.com/repos/Automattic/simplenote-electron/releases/latest
    return_content: true
  register: json_reponse

  get_url:
    url: "{{ json_reponse.json.amd64 }}"
    dest: ./test-latest.tar.gz


