---

  ####################
  ## Install raambox
  ####################
- stat: path=/opt/Telegram/Telegram
  register: telegram_stat

- name: Installing Telegram
  unarchive:
     src: https://telegram.org/dl/desktop/linux
     dest: /opt
     remote_src: yes
  when: not telegram_stat.stat.exists

  ####################
  ## Install jitsi
  ####################
- stat: path=/usr/bin/jitsi
  register: jitsi_stat

- name: Downloading jitsi dependencies
  get_url: url=https://download.jitsi.org/jitsi/debian/jitsi-archive-keyring_1.0.1_all.deb dest=/tmp/jitsi-keyring.deb
  when: not jitsi_stat.stat.exists

- name: Downloading jitsi
  get_url: url=https://download.jitsi.org/jitsi/debian/jitsi_2.10.5550-1_amd64.deb dest=/tmp/jitsi.deb
  when: not jitsi_stat.stat.exists

- name: Installing jitsi
  apt: deb={{item}}
  with_items:
    - /tmp/jitsi-keyring.deb
    - /tmp/jitsi.deb
  when: not jitsi_stat.stat.exists

  ####################
  ## Install signal
  ####################
  ##- name: Installing signal repo
  ##  apt_repository:
  ##     repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
  ##     state: present
  ##     filename: 'signal'
  ##
  ##- name: Installing signal
  ##  apt: name=signal-desktop

  ####################
  ## Install keybase
  ####################
- stat: path=/usr/bin/run_keybase
  register: keybase_stat

- name: Downloading keybase
  get_url: url=https://prerelease.keybase.io/keybase_amd64.deb dest=/tmp/keybase_amd64.deb
  when: not keybase_stat.stat.exists

- name: Installing keybase
  apt: deb=/tmp/keybase_amd64.deb
  when: not keybase_stat.stat.exists


  ####################
  ## Install raambox
  ####################
  ##- stat: path=/opt/Rambox/rambox
##  register: rambox_stat
##
##- name: Creates rambox directory
##  file: path=/opt/Rambox state=directory
##
##- name: Installing rambox
##  unarchive:
##     src: https://getrambox.herokuapp.com/download/linux_64?filetype=deb
##     dest: /opt/Rambox
##     remote_src: yes
##     extra_opts: [--strip-components=1]
##  when: not rambox_stat.stat.exists
##
