---

  ####################
  ## Install vivaldi
  ####################
- stat: path=/usr/bin/vivaldi
  register: vivaldi_stat

- name: Downloading vivaldi
  get_url: url=https://downloads.vivaldi.com/stable/vivaldi-stable_1.14.1077.55-1_amd64.deb dest=/tmp/vivaldi.deb
  when: not vivaldi_stat.stat.exists

- name: Installing vivaldi
  apt: deb={{item}}
  with_items:
    - /tmp/vivaldi.deb
  when: not vivaldi_stat.stat.exists

