---

- name: Create list
  set_fact:
     my_list:
       - di
       - f2fs-tools
       - btrfs-progs
       - gparted

- name: Install Packages
  apt: name={{ my_list }} state=present # update_cache=yes
 
